//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAngular2_DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
    }
}
